In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv(r"C:\Users\HP\Documents\Project For Data science\bakery_unclean_data.csv")

In [3]:
df.head()

,date,route_id,product_name,quantity_produced,quantity_dispatched,quantity_sold,quantity_returned,day_of_week,is_school_term,is_payday_cycle,notes
0,2026-04-16,route d,Mandazi,185.0,31.0,31.0,0.0,Thursday,0,1,NaN
1,03/02/2026,Route C,Bread,190.0,41.0,41.0,0.0,Tuesday,1,1,NaN
2,07/01/2026,Route C,Cake,171.0,35.0,35.0,0.0,Wednesday,1,0,NaN
3,03-24-2026,Route D,Mandazi,NaN,74.0,74.0,0.0,Tuesday,1,0,NaN
4,04/03/2026,Route D,Mandazi,330.0,60.0,60.0,0.0,Wed,1,0,NaN

In [9]:
# the rows of the dataset
df.shape[0]

2699

In [10]:
# the columns of the dataset
df.shape[1]

11

In [11]:
# the imfomation about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2699 entries, 0 to 2698
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 2699 non-null   object
 1   route_id             2699 non-null   object
 2   product_name         2699 non-null   object
 3   quantity_produced    2649 non-null   float64
 4   quantity_dispatched  2647 non-null   float64
 5   quantity_sold        2612 non-null   float64
 6   quantity_returned    2633 non-null   float64
 7   day_of_week          2546 non-null   object
 8   is_school_term       2699 non-null   object
 9   is_payday_cycle      2699 non-null   object
 10  notes                217 non-null    object
dtypes: float64(4), object(7)
memory usage: 232.1+ KB

In [15]:
# displaying all the names and total number of variables
df.columns

Index(['date', 'route_id', 'product_name', 'quantity_produced',
       'quantity_dispatched', 'quantity_sold', 'quantity_returned',
       'day_of_week', 'is_school_term', 'is_payday_cycle', 'notes'],
      dtype='object')

In [14]:
df.describe()

,quantity_produced,quantity_dispatched,quantity_sold,quantity_returned
count,2649.00000,2647.000000,2612.000000,2633.000000
mean,253.08456,50.783151,51.205972,-0.049373
std,146.05946,29.874198,30.365570,0.494491
min,-10.00000,7.000000,7.000000,-5.000000
25%,140.00000,28.000000,28.000000,0.000000
50%,219.00000,44.000000,44.000000,0.000000
75%,340.00000,67.500000,68.000000,0.000000
max,876.00000,196.000000,196.000000,0.000000

In [16]:
df.isnull().sum()

date                      0
route_id                  0
product_name              0
quantity_produced        50
quantity_dispatched      52
quantity_sold            87
quantity_returned        66
day_of_week             153
is_school_term            0
is_payday_cycle           0
notes                  2482
dtype: int64

In [17]:
#remove exact duplicates
initial_rows = len(df)
df.drop_duplicates(inplace = True)

In [18]:
df.isnull().sum()

date                      0
route_id                  0
product_name              0
quantity_produced        49
quantity_dispatched      50
quantity_sold            86
quantity_returned        64
day_of_week             150
is_school_term            0
is_payday_cycle           0
notes                  2433
dtype: int64

In [19]:
# standardize dates & reconstruct day of the week
df['date'] =pd.to_datetime(df['date'],format = 'mixed', dayfirst = True)
df['day_of_week'] = df['date'].dt.day_name()

In [20]:
df.isnull().sum()

date                      0
route_id                  0
product_name              0
quantity_produced        49
quantity_dispatched      50
quantity_sold            86
quantity_returned        64
day_of_week               0
is_school_term            0
is_payday_cycle           0
notes                  2433
dtype: int64

In [21]:
#clean & standardize categorical text
df['route_id'] = df['route_id'].astype(str).str.strip().str.title()
df['route_id']=df['route_id'].replace({'Rt' :'Route'})

In [22]:
df['product_name'] = df['product_name'].astype(str).str.strip().str.title()
df['product_name'] = df['product_name'].replace({'Bred':'Bread','Breads':'Bread','Mandazis':'Mandazi'})

In [25]:
# normalize booeln Indicators
bool_cols = ['is_school_term', 'is_payday_cycle']
for col in bool_cols:
    df[col] = df[col].astype(str).str.lower().str.strip()
    df[col] = df[col].map({'1': 1, '0': 0, 'yes': 1, 'no': 0, 'true': 1, 'false': 0})
    df[col] = df[col].fillna(0).astype(int)

In [26]:
df.isnull().sum()

date                      0
route_id                  0
product_name              0
quantity_produced        49
quantity_dispatched      50
quantity_sold            86
quantity_returned        64
day_of_week               0
is_school_term            0
is_payday_cycle           0
notes                  2433
dtype: int64

In [27]:
#handle missing values
df['quantity_produced'] =df['quantity_produced'].ffill()

In [28]:
df['quantity_dispatched'] =df['quantity_dispatched'].ffill()

In [29]:
df['quantity_sold'] =df['quantity_sold'].ffill()

In [30]:
df['quantity_returned'] =df['quantity_returned'].ffill()

In [31]:
df['quantity_dispatched'] =df['quantity_dispatched'].ffill()

In [32]:
df['notes'] =df['notes'].ffill()

In [33]:
df.isnull().sum()

date                   0
route_id               0
product_name           0
quantity_produced      0
quantity_dispatched    0
quantity_sold          0
quantity_returned      0
day_of_week            0
is_school_term         0
is_payday_cycle        0
notes                  9
dtype: int64

In [34]:
df['notes'] =df['notes'].bfill()

In [35]:
df.isnull().sum()

date                   0
route_id               0
product_name           0
quantity_produced      0
quantity_dispatched    0
quantity_sold          0
quantity_returned      0
day_of_week            0
is_school_term         0
is_payday_cycle        0
notes                  0
dtype: int64

In [36]:
# Median imputation grouped by product to preserve route/product baselines
df[col] = df.groupby('product_name')[col].transform(lambda x: x.fillna(x.median()))

In [37]:
df.isnull().sum()

date                   0
route_id               0
product_name           0
quantity_produced      0
quantity_dispatched    0
quantity_sold          0
quantity_returned      0
day_of_week            0
is_school_term         0
is_payday_cycle        0
notes                  0
dtype: int64

In [38]:
# winsorize extreme outliers at 99th percentile
upper_bound = df[col].quantile(0.99)
df[col] = df[col].clip(upper=upper_bound)

In [40]:
# fix logical errors ; sold > dispached
logical_fix = df['quantity_sold'] > df['quantity_dispatched']
df.loc[logical_fix, 'quantity_sold']=df.loc[logical_fix, 'quantity_dispatched']
df.loc[logical_fix, 'quantity_returned'] = 0

In [ ]:
#future engineering
df[]